sudo: required
services:
    - docker

before_install:
    - docker build -t tito/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run tito/react-test npm test -- --coverage

after_success:
    - docker build -t titosebastien/multi-client ./client
    - docker build -t titosebastien/multi-nginx ./nginx
    - docker build -t titosebastien/multi-server ./server
    - docker build -t titosebastien/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin docker.io
    # Take those images and push them to docker hub
    - docker push titosebastien/multi-client
    - docker push titosebastien/multi-nginx
    - docker push titosebastien/multi-server
    - docker push titosebastien/multi-worker
